# Logistic Regression From scratch

## Data Prepration

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [6]:
df = pd.read_csv("data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [13]:
df = df.drop(columns={"id","Unnamed: 32"}, errors= "ignore")
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [12]:
df["diagnosis"] = df["diagnosis"].map({"M": 1, "B" : 0})

spliting X and y

In [16]:
X =  df.drop(columns=["diagnosis"]).values
y = df["diagnosis"].values

In [17]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (569, 30)
y shape: (569,)

scaling

In [18]:
mean = X.mean(axis=0)
std = X.std(axis=0)

X_scaled = (X - mean ) / std

train test spliting

In [23]:
np.random.seed(42)
shuffle_idx =  np.random.permutation(len(X_scaled))

X_scaled = X_scaled[shuffle_idx]
y = y[shuffle_idx]
split = int(len(X_scaled) * 0.8)

X_train = X_scaled[:split]
y_train = y[:split]

X_test = X_scaled[split:]
y_test = y[split:]

In [24]:
print("Train shapes:", X_train.shape, y_train.shape)
print("Test shapes:", X_test.shape, y_test.shape)

Train shapes: (455, 30) (455,)
Test shapes: (114, 30) (114,)

## Sigmoid Function (Vectorized)

In [25]:
def sigmoid(z):
    z = np.clip(z, -500,500)

    return 1 / (1 + np.exp(-z))

## Hypothesis Function (Vectorized)

In [ ]:
def hypothesis(X , w, b):
    z = X @ w + b
    
    return sigmoid(z)

## Cost Function(Log Loss)

In [30]:
def compute_cost(h, y):

    m = len(y)
    eps = 1e-15

    h = np.clip(h,eps, 1-eps)

    cost = - (1/m) * np.sum(y*np.log(h) + (1-y)*np.log(1-h))
    return cost

## Gradients

In [ ]:
def compute_gradients(X, h, y):

    m = len(y)
    error = h - y 

    dw = (1 / m) * (X.T @ error)
    db = (1/m) * np.sum(error)  

    return dw, db

## Gradient Descent Loop

In [34]:
def gradient_descent(X, y, w, b, learning_rate, iterations):
    m = len(y)
    
    cost_history = []
    w_history = []

    for i in range(iterations):

        h = hypothesis(X, w, b)

        cost = compute_cost(h, y)


        dw, db = compute_gradients(X, h, y)

        w = w - learning_rate * dw
        b = b - learning_rate * db

        cost_history.append(cost)
        w_history.append(w.copy())

        if i % 100 == 0:
            print(f"Iteration {i}, Cost: {cost}")

    return w, b, cost_history, w_history

## Predict Probabiltiy and Predict Class

In [38]:
def predict_proba(X, w,b):
    return hypothesis(X, w, b)

def predict_class(X, w, b, threshold = 0.5):

    probs = predict_proba(X, w, b)
    return (probs >= threshold).astype(int)

## Accuracy Calculation

In [39]:
def accuracy_score_manual(y_true, y_pred):
    return np.mean(y_true == y_pred)

In [43]:
def confusion_matrix_manual(y_true, y_pred):
    tp = np.sum((y_pred == 1) & (y_true == 1))
    tn = np.sum((y_pred == 0) & (y_true == 0))
    fp = np.sum((y_pred == 1) & (y_true == 0))
    fn = np.sum((y_pred == 0) & (y_true == 1))
    
    return tp, tn, fp, fn

In [44]:
def precision_manual(tp, fp):
    eps = 1e-15
    return tp / (tp + fp + eps)

In [45]:
precision = precision_manual(tp, fp)
print("Precision:", precision)

NameError: name 'tp' is not defined